server:
  port: 8089 
  
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: micro_service_user
        uri: http://localhost:8082/
        predicates:
        - Path=/msuser/**
      - id: micro_service_employe
        uri: http://localhost:8083/
        predicates:
        - Path=/msemploye/**

      - id: MicroService-Produit
        uri: http://localhost:8084/
        predicates:
        - Path=/api/produit/**
        

 main
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka