server:
  port: 8089 

spring:
  application:
    name: gateway
    
  cloud:
    gateway:
      routes:
      - id: micro_service_user
        uri: http://micro_service_user:8082/
        predicates:
        - Path=/msuser/**
      - id: micro_service_employe
        uri: http://micro_service_user:8083/
        predicates:
        - Path=/msemploye/**
        
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
  
      