server:
  port: 8089 

spring:
  application:
    name: api-gateway
    
  cloud:
    gateway:
      routes:
      - id: micro_service_user
        uri: http://host.docker.internal:8082/
        predicates:
            - Path=/msuser/**
      - id: micro_service_employe
        uri: http://host.docker.internal:8083/
        predicates:
            - Path=/msemploye/**
      - id: micro_service_fournisseur
        uri: http://host.docker.internal:8090/
        predicates:
            - Path=/api/fournisseur/**
      - id: micro_service_emprunt
        uri: http://host.docker.internal:8091/
        predicates:
            - Path=/api/emprunt/**
      - id: commande-client
        uri: http://host.docker.internal:8085/
        predicates:
            - Path=/api/commande/**
      - id: facture
        uri: http://host.docker.internal:3000/
        predicates:
            - Path=/api/facture/**
      - id: produit-client
        uri: http://host.docker.internal:8084/
        predicates:
            - Path=/api/produit/**
      - id: depot
        uri: http://host.docker.internal:3001/
        predicates:
            - Path=/api/depot/**
      - id: micro_service_projet
          uri: http://host.docker.internal:8093/
          predicates:
            - Path=/msprojet/**
      - id: micro_service_collaborateur
          uri: http://host.docker.internal:8092/
          predicates:
            - Path=/mscollaborateur/**
      
        
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

  
      