version: '3'
services:
  mysqldb:
    platform: linux/x86_64
    image: "mysql:5.6"
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: microServiceProduit
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: mysql        
  discovery:
    image: discovery
    build: Eureka-Server
    ports:
      - 8761:8761  
  micro_service_user:
    image: micro_service_user
    build: MicroServiceUsers
    depends_on:
      - discovery
      - mysqldb 
    ports:
      - 8082:8082 
  micro_service_employe:
    image: micro_service_employe
    build: MicroServiceEmploye
    depends_on:
      - discovery
      - mysqldb 
    ports:
      - 8083:8083
  api-gateway:
    image: api-gateway
    build: Cloud-Gateway-1
    depends_on:
      - discovery
    ports:
      - 8089:8089
  micro_service_fournisseur:
    image: micro_service_fournisseur
    build: MicroService-Fournisseur
    depends_on:
      - discovery
      - mysqldb 
    ports:
      - 8090:8090
  micro_service_emprunt:
    image:  micro_service_emprunt
    build: MicroserviceEmprunt-Nodejs
    environment:
      NODE_ENV: production
    ports:
      - 8091:8091
  commande-client:
    image: microservice-commande
    build: MicroService-Commande
    depends_on:
      - discovery
      - mysqldb
    ports:
      - 8085:8085
  facture:
    image: facture
    build: nodeserviceFacture
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
  produit-client:
    image: microservice-produit
    build: MicroService-Produit
    depends_on:
      - discovery
      - mysqldb
    ports:
      - 8084:8084
  depot:
    image: depot
    build: Microservice-Depot-Node
    environment:
      NODE_ENV: production
    ports:
      - 3001:3001
  micro_service_colab:
    image: micro_service_colab
    build: collaborateur-service
    depends_on:
      - discovery
    ports:
      - 8092:8092
  micro_service_projet:
    image: micro_service_projet
    build: projet-service
    depends_on:
      - discovery
    ports:
      - 8093:8093
      
      
  