version: '3.4'

services:
  microservicedepotnode:
    image: microservicedepotnode
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
