version: '3.4'

services:
  microserviceempruntnodejs:
    image: microserviceempruntnodejs
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8091:8091
